basePath: /
definitions:
host: 10.244.79.96:9016
info:
  contact: {email: james@esixteen.com, name: eSixteen.co }
  description: Earn bitcoin by transcoding video.
  title: TranscodeE16
  x-21-category: utilities
  x-21-github-project-url: https://github.com/pooleja/TranscodeE16
  x-21-keywords: [stats, speed, video, transcode, download, test, iot, sensor]
  x-21-quick-buy: "$ 21 buy http://10.244.79.96:9016/"
paths:
  /price:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Price for transcoding specified video
          schema:
            properties:
              server: {$ref: '#/definitions/Server'}
      summary: Returns stats about the device.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
