basePath: /
definitions:
  Temperature:
    properties:
      timestamp: {type: string, format: "YYYY-MM-DD 24HH:MM:SS.USSS"}
      temperature: {type: number, format: float}
    type: object
host: 10.244.79.96:6016
info:
  contact: {email: james@microtrx.com, name: eSixteen.co }
  description: Get temperature data on demand for bitcoin.
  title: SensorE16
  x-21-category: utilities
  x-21-github-project-url: https://github.com/pooleja/sensorE16
  x-21-keywords: [temperature, sensor]
  x-21-quick-buy: "$ 21 buy http://<ZEROTIER IP>:6016/"
  x-21-total-price: {max: 5, min: 5}
  x-21-implements-meta: {
        "x-sensor21-city": "{CITY}",
        "x-sensor21-state": "{STATE}",
        "x-sensor21-country": "{COUNTRY}"
    }
paths:
  /:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Air temperature for the location of the server and location information.
          schema:
            properties:
              temperature: {$ref: '#/definitions/Temperature'}
      summary: Returns temperature in degrees C.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
