basePath: /
definitions:
host: 10.244.79.96:8016
info:
  contact: {email: james@microtrx.com, name: eSixteen.co }
  description: Get machine upload/download stats on demand for bitcoin.
  title: SpeedE16
  x-21-category: utilities
  x-21-github-project-url: https://github.com/pooleja/SpeedE16
  x-21-keywords: [stats, speed, upload, download, test, iot, sensor]
  x-21-quick-buy: "$ 21 buy http://10.244.79.96:8016/"
  x-21-total-price: {max: 5, min: 5}
paths:
  /:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Stats for the location and hardware of the server.
          schema:
            properties:
              server: {$ref: '#/definitions/Server'}
      summary: Returns stats about the device.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
